language: python

cache:
  directories:
  - $HOME/.cache/pip

python:
  - "3.8"

envs:
  - REQUIRED_PYTHON="python3"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda3
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - chmod +x $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/condabin:$PATH
  - conda update --yes conda
  # create cookiecutter environment
  - conda create -n cookiecutter --yes python=3.8
  - conda init bash
  - . ~/.bashrc
  - conda activate cookiecutter
  - pip install cookiecutter
  - pip install ruamel.yaml

script:
  - pwd
  # build a cookiecutter project test-env
  - cookiecutter --config-file .cookiecutter-easydata-test.yml . -f --no-input
  - conda deactivate
  # create the environment from test-env
  - cd test-env
  - make create_environment
  - conda activate test-env
  - touch environment.yml
  - make update_environment
  # create test dataset
  - python src/tests/make_test_datasets.py
  # run tests on the src module
  - export CI_RUNNING=yes
  - make test_with_coverage
  # test notebooks in docs
  - pytest -v ../docs/test_docs.py

after_success:
  - conda activate test-env
  - coveralls