language: python

cache:
  directories:
  - $HOME/.cache/pip

python:
  - "3.8"

envs:
  - REQUIRED_PYTHON="python3"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda3
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - chmod +x $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/condabin:$PATH
  - conda update --yes conda
  # create the testing environment
  - cd \{\{\ cookiecutter.repo_name\ \}\}
  - conda env update -n test-env -f environment.yml
  - conda activate test-env
  - test_environment environment.$(ARCH).lock.yml

script:
  - cd \{\{\ cookiecutter.module_name\ \}\}
  - coverage run -m pytest --doctest-modules --doctest-continue-on-failure --verbose

after_success:
  - coveralls