site_name: Easydata
site_description: A project template and directory structure for reproducible and collaborative Python-based data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/hackalog/cookiecutter-easydata
copyright: CCBY 4.0
google_analytics: ['UA-54096005-4', 'auto']
theme: readthedocs
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Opinions: opinions.md
  - Datasets: datasets.md
  - 'Example Notebooks':
      - 'Basic Starter Notebook': 00-xyz-sample-notebook.ipynb
      - 'Creating a dataset from a csv file': Add-csv-template.ipynb
      - 'Creating a derived dataset from a single function': Add-derived-dataset.ipynb
plugins:
  - mkdocs-jupyter