{% macro pyver() -%}
{% if cookiecutter.python_version == 'latest' -%}
  - python=3
{% else -%}
  - python={{ cookiecutter.python_version }}
{% endif -%}
{% endmacro -%}
name: {{ cookiecutter.repo_name }}
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - umap-learn
    - gdown
  - setuptools
  - wheel
  - git>=2.5  # for git worktree template updating
  - sphinx
  - bokeh
  - click
  - colorcet
  - coverage
  - datashader
  - holoviews
  - matplotlib
  - pytest-cov
  - jupyter
  - scikit-learn
  - scipy
  - joblib
  - nb_conda_kernels<2.2.0  # nb_conda_kernels issue #158
  - pandas
  - requests
  - pathlib
{{ pyver()|indent(2, true) }}
