{% macro pyver() -%}
{% if cookiecutter.python_version == 'latest' -%}
  - python=3
{% else -%}
  - python={{ cookiecutter.python_version }}
{% endif -%}
{% endmacro -%}
name: {{ cookiecutter.repo_name }}
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
  - pathlib
{{ pyver()|indent(2, true) }}
