site_name: Cookiecutter Easydata
site_description: A project template and directory structure for Python reproducible and collaborative data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/hackalog/cookiecutter-easydata
copyright: CCBY 4.0
google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
  - Opinions: opinions.md
  - Datasets: datasets.md